stages:
  - build
  - test
  - upload

# TODO: Move to `variables` section when possible.
# https://gitlab.com/gitlab-org/gitlab-runner/issues/1809
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export GRADLE_OPTS='-Dorg.gradle.daemon=false'

# Build the JAR.
jar:
  stage:       build
  image:       openjdk:8
  script:
    - ./gradlew shadowJar
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build # Actually, caching build does not work because of files' access / modification time. Probably will be working one day.
  artifacts:
    paths:
      - build/libs/packt4free-all.jar
    expire_in: 1 hour

# Run unit tests.
# Actually, unit tests parse https://www.packtpub.com/packt/offers/free-learning, so it is not "true" unit tests.
unit:
  stage:       test
  image:       openjdk:8
  script:
    - ./gradlew test
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build # Actually, caching build does not work because of files' access / modification time. Probably will be working one day.

# Upload fat JAR to S3.
s3:
  stage: upload
  image:
    name: nbrown/aws-cli:latest
    entrypoint:
      - ''
  script:
    - aws s3 cp build/libs/packt4free-all.jar s3://${ARTIFACTS_BUCKET}/${CI_COMMIT_SHA}.jar
  only:
    - master
