stages:
  - lint
  - build
  - test
  - upload
  - deploy

# Check if logo.png in the root of the repo corresponds to the content of assets/src/logo.svg.
logo:
  stage:         lint
  image:         madhead/imagemagick
  script:
    - convert -background none -density 300 -resize 128x128 src/main/assets/logo.svg logo.check.png
    - magick compare -verbose -metric ae logo.png logo.check.png diff.png
  artifacts:
    name:        $CI_COMMIT_SHA-$CI_JOB_NAME
    paths:
      - diff.png
    expire_in:   1 hour
    when:        on_failure

# Validate CloudFormation template.
logo:
  stage:         lint
  image:
    name:        nbrown/aws-cli:latest
    entrypoint:
      - ''
  script:
    - aws cloudformation validate-template --template-body file://./aws/packt4free.yml

# Build the JAR.
jar:
  stage:         build
  image:         openjdk:8
  # TODO:        Move to `variables` section when possible.
  # https://gitlab.com/gitlab-org/gitlab-runner/issues/1809
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
  script:
    - ./gradlew shadowJar
  cache:
    key:         $CI_JOB_NAME
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build # Actually, caching build does not work because of files' access / modification time. Probably will be working one day.
  artifacts:
    name:        $CI_COMMIT_SHA-$CI_JOB_NAME
    paths:
      - build/libs/packt4free-all.jar
    expire_in:   1 hour

# Run unit tests.
# Actually, unit tests parse https://www.packtpub.com/packt/offers/free-learning, so it is not "true" unit tests.
unit:
  stage:         test
  image:         openjdk:8
  # TODO:        Move to `variables` section when possible.
  # https://gitlab.com/gitlab-org/gitlab-runner/issues/1809
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
  script:
    - ./gradlew test
  cache:
    key:         $CI_JOB_NAME
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build # Actually, caching build does not work because of files' access / modification time. Probably will be working one day.

# Upload fat JAR to S3.
s3:
  stage:         upload
  image:
    name:        nbrown/aws-cli:latest
    entrypoint:
      - ''
  script:
    - aws s3 cp build/libs/packt4free-all.jar s3://${ARTIFACTS_BUCKET}/${CI_COMMIT_SHA}.jar
  only:
    - master

# Deploy Lambda.
deploy:
  stage:         deploy
  image:
    name:        nbrown/aws-cli:latest
    entrypoint:
      - ''
  script:
    - aws cloudformation deploy --template-file aws/packt4free.yml --stack-name packt4free --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --parameter-overrides "sha1=${CI_COMMIT_SHA}"
  environment:
    name:        production
  only:
    - master
