---
stages:
  - build
  - test

# Build the JAR.
jar:
  stage:         build
  image:         openjdk:8
  # TODO:        Move to `variables` section when possible.
  # https://gitlab.com/gitlab-org/gitlab-runner/issues/1809
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
  script:
    - ./gradlew shadowJar
  cache:
    key:         $CI_JOB_NAME
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build # Actually, caching build does not work because of files' access / modification time. Probably will be working one day.
  artifacts:
    name:        $CI_COMMIT_SHA-$CI_JOB_NAME
    paths:
      - build/libs/packt4free-all.jar
    expire_in:   1 hour

# Run unit tests.
# Actually, unit tests parse https://www.packtpub.com/packt/offers/free-learning, so it is not "true" unit tests.
unit:
  stage:         test
  image:         openjdk:8
  # TODO:        Move to `variables` section when possible.
  # https://gitlab.com/gitlab-org/gitlab-runner/issues/1809
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
  script:
    - ./gradlew test
  cache:
    key:         $CI_JOB_NAME
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build # Actually, caching build does not work because of files' access / modification time. Probably will be working one day.

# Check if logo.png in the root of the repo corresponds to the content of assets/src/logo.svg.
logo:
  stage:         test
  image:         madhead/imagemagick
  script:
    - convert -background none -density 300 -resize 128x128 src/main/assets/logo.svg logo.check.png
    - magick compare -verbose -metric ae logo.png logo.check.png diff.png
  allow_failure: true
  artifacts:
    name:        $CI_COMMIT_SHA-$CI_JOB_NAME
    paths:
      - diff.png
    expire_in:   1 hour
    when:        on_failure
